platform :ios, ‘8.0’
inhibit_all_warnings!
target “ScodeProject” do
pod 'AFNetworking', '~> 3.1.0'
pod ‘MBProgressHUD’
pod ‘MJRefresh’
pod 'Masonry', '~> 1.0.0'
pod 'MJExtension'
pod 'SVProgressHUD'

end
